{{-- SEO Meta Tags - Generated by MetaService --}}
@php
    // Initialize MetaService if not already done
    if (!isset($metaService)) {
        $metaService = app(App\Services\MetaService::class);
    }
    
    try {
        $meta = $metaService->getAllMeta();
        $metaTags = $meta['meta'] ?? [];
        $openGraph = $meta['openGraph'] ?? [];
        $twitterCard = $meta['twitterCard'] ?? [];
        $schemaOrg = $meta['schemaOrg'] ?? [];
    } catch (\Exception $e) {
        // Fallback meta tags
        $metaTags = [
            'title' => config('app.name', 'PlaySudoku'),
            'description' => 'Play Sudoku online for free!',
            'keywords' => 'sudoku, puzzle, game, online',
            'author' => 'PlaySudoku',
            'robots' => 'index, follow',
            'viewport' => 'width=device-width, initial-scale=1.0',
        ];
        $openGraph = [];
        $twitterCard = [];
        $schemaOrg = [];
        \Log::warning('Failed to load meta tags: ' . $e->getMessage());
    }
@endphp

{{-- Basic Meta Tags --}}
<title>{{ $metaTags['title'] }}</title>
<meta name="description" content="{{ $metaTags['description'] }}">
<meta name="keywords" content="{{ $metaTags['keywords'] }}">
<meta name="author" content="{{ $metaTags['author'] }}">
<meta name="robots" content="{{ $metaTags['robots'] }}">
<meta name="viewport" content="{{ $metaTags['viewport'] }}">

{{-- Canonical URL --}}
@if(isset($metaTags['canonical']))
<link rel="canonical" href="{{ $metaTags['canonical'] }}">
@endif

{{-- Open Graph Tags --}}
@foreach($openGraph as $property => $content)
<meta property="{{ $property }}" content="{{ $content }}">
@endforeach

{{-- Twitter Card Tags --}}
@foreach($twitterCard as $name => $content)
<meta name="{{ $name }}" content="{{ $content }}">
@endforeach

{{-- Schema.org JSON-LD --}}
@if(!empty($schemaOrg))
<script type="application/ld+json">
{!! json_encode($schemaOrg, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) !!}
</script>
@endif
